# Dependencies
markdown:         kramdown
highlighter:      rouge # changed from `pygments` as github says so

# Permalinks
permalink:        pretty

# Setup
title:            'Peter Otieno'
tagline:          'Data Analysis|Data Science|Business Intelligence|DataViz'
description:      'Excelsior'
url:              https://peter-akworo.github.io/
baseurl:          ''
paginate:         5
paginate_path:    '/blog/page:num/'

author:
  name: 'Peter Otieno'
  email: 'datanomadke[at]gmail[dot]com'
  github: peter-akworo
  twitter: datanomadke
  linkedin: peter-onyango/
  email_md5: c2c283745c9b7aae554054a38e953f16
  emailalt_md5: c2c283745c9b7aae554054a38e953f16
  disqus_shortname: peter-akworo-github-io
  google_analytics_id: UA-129733925-1
  google_analytics_url: peter-akworo.github.io
  bio: 'Data Analysis|Data Science|Business Intelligence|DataViz'
